---
  extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - prettier
  env:
    node: true
    mocha: true
    es6: true
  parser: '@typescript-eslint/parser'
  parserOptions:
    sourceType: module
    ecmaFeatures:
      modules: true
  rules:
    '@typescript-eslint/no-explicit-any': 0
    'max-len': 0
    'no-case-declarations': 0
    'semi': 0
    'space-before-function-paren': 0
    'arrow-parens': 0
    generator-star-spacing:
      - 2
      - before: true
        after: true
    no-shadow: 0
    import/no-unresolved: 0
    import/extensions: 0
    require-yield: 0
    no-param-reassign: 0
    comma-dangle: 0
    no-underscore-dangle: 0
    no-control-regex: 0
    func-names: 0
    no-unused-expressions: 0
    prefer-arrow-callback: 1
    no-use-before-define:
      - 2
      - functions: false
